name: CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  setup:
    uses: zhumeisongsong/shared-actions/.github/workflows/pnpm-setup.yml@main

  lint:
    needs: setup
    uses: zhumeisongsong/shared-actions/.github/workflows/eslint.yml@main
    
  type-check:
    needs: setup
    uses: zhumeisongsong/shared-actions/.github/workflows/ts-type-check.yml@main