name: CI

on:
  pull_request:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Print the current directory (optional)
    - name: Print current directory
      run: pwd

    - name: List files in the root directory
      run: ls -la

  setup:
    uses: zhumeisongsong/shared-actions/.github/workflows/pnpm-setup.yml@main

  lint:
    needs: setup
    uses: zhumeisongsong/shared-actions/.github/workflows/nextjs-lint.yml@main
    
  type-check:
    needs: setup
    uses: zhumeisongsong/shared-actions/.github/workflows/nextjs-type-check.yml@main