name: CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  setup:
    uses: zhumeisongsong/shared-actions/.github/workflows/reusable-pnpm-setup.yml@main

  test:
    needs: setup
    uses: zhumeisongsong/shared-actions/.github/workflows/reusable-nx-test.yml@main

  lint:
    needs: setup
    uses: zhumeisongsong/shared-actions/.github/workflows/reusable-nx-lint-run-many.yml@main
    
  type-check:
    needs: setup
    uses: zhumeisongsong/shared-actions/.github/workflows/reusable-nx-type-check-run-many.yml@main
  
  buildable:
    needs: [test, lint, type-check]
    uses: zhumeisongsong/shared-actions/.github/workflows/reusable-nx-build.yml@main