name: Publish Packages

on:
  push:
    branches:
      - main

jobs:
  setup:
    uses: zhumeisongsong/shared-actions/.github/workflows/pnpm-setup.yml@main

  publish:
    name: Publish packages to npm
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # needed for provenance data generation
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # need to fetch all the tags
      
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          registry-url: https://registry.npmjs.org/

      - name: Restore Pnpm Store and Install Dependencies
        uses: zhumeisongsong/shared-actions/.github/actions/pnpm@main

      - name: Print Environment Info
        run: pnpx nx report
        shell: bash

      - name: Publish packages
        run: pnpx nx release publish
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
          NPM_CONFIG_PROVENANCE: true