name: Publish Packages

on:
  push:
    branches:
      - main

permissions:
  id-token: write  # Grant write access to the id-token permission
  contents: read   # Adjust other permissions as necessary
  packages: write  # Needed if you are publishing packages

jobs:
  setup:
    uses: zhumeisongsong/shared-actions/.github/workflows/reusable-pnpm-setup.yml@main
