name: Publish

on:
  # Run manually using the GitHub UI
  workflow_dispatch:
    inputs:
      version:
        description: "Version to publish"
        required: false
        default: ""
  # ...or whenever a GitHub release gets created
  release:
    types: [published]

jobs:
  setup:
    uses: zhumeisongsong/shared-actions/.github/workflows/pnpm-setup.yml@main

  publish:
    name: Publish to npm
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # needed for provenance data generation
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # need to fetch all the tags
      
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: pnpm install
        shell: bash

      - name: Print Environment Info
        run: pnpx nx report
        shell: bash

      - name: Publish packages
        run: npx nx release publish
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
          NPM_CONFIG_PROVENANCE: true