name: Publish Packages

on:
  push:
    branches:
      - main

permissions:
  contents: write # to be able to publish a GitHub release
  issues: write # to be able to comment on released issues
  pull-requests: write # to be able to comment on released pull requests
  id-token: write # to enable use of OIDC for npm provenance

jobs:
  setup:
    uses: zhumeisongsong/shared-actions/.github/workflows/reusable-pnpm-setup.yml@main

  publish-packages:
    name: Publish packages
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Nx set shas
        uses: nrwl/nx-set-shas@v4

      - name: Restore pnpm store and install dependencies
        uses: zhumeisongsong/shared-actions/.github/actions/pnpm@main

      - name: Setup npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cat << EOF > "$HOME/.npmrc"
           //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF
        shell: bash

      - name: Verify NPM Authentication
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm whoami || pnpm exec npm whoami

      - name: Build
        run: pnpm nx run-many -target=build --parallel=3

      - name: Publish to npm
        env:
          GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          pnpm nx run-many -target=release
          pnpm semantic-release-plus
