name: Publish GitHub Packages

on:
  push:
    branches:
      - main
    paths:
      - 'github-packages/**'
  pull_request:
    paths:
      - 'github-packages/**'

permissions:
  contents: write # to be able to publish a GitHub release
  packages: write # to be able to publish a GitHub package
  issues: write # to be able to comment on released issues
  pull-requests: write # to be able to comment on released pull requests

jobs:
  setup:
    uses: zhumeisongsong/shared-actions/.github/workflows/reusable-pnpm-setup.yml@main

  publish-github-packages:
    name: Publish github packages
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Nx set shas
        uses: nrwl/nx-set-shas@v4

      - name: Restore pnpm store and install dependencies
        uses: zhumeisongsong/shared-actions/.github/actions/pnpm@main

      - name: Build
        run: pnpm nx run-many -target=build --parallel=3 --projects="github-packages/*"

      - name: Publish to github packages
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NPM_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          pnpm nx run-many -target=release --projects="github-packages/*"
